spring.application.name=aichat
spring.datasource.url=jdbc:postgresql://localhost:5432/ai_talk
spring.datasource.username=postgres
spring.datasource.password=user

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.user.name=ysf
spring.security.user.password=ysf
app.image-storage.base-path=C:/Users/youssef/Files
app.image-storage.allowed-mime-types=image/jpeg,image/png,image/webp,image/gif,application/pdf,application/octet-stream
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.threads.virtual.enabled=true
spring.mvc.async.request-timeout=300000
server.port=8090


spring.mail.port=587
spring.mail.host=smtp.gmail.com
spring.mail.username=youssefmasmoudi05@gmail.com
spring.mail.password=frge lxcr wjzb kwfy
spring.mail.properties.mail.smtp.auth = true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.auto-commit=true
spring.datasource.hikari.connection-timeout=1200000
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.max-lifetime=1800000

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
spring.servlet.multipart.resolve-lazily=true
spring.graphql.schema.printer.enabled=true
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
spring.graphql.schema.locations=classpath:graphql/
